<?php
echo "<!doctype html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "  <meta charset=\"utf-8\">\n";
echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "  <!-- Bootstrap CSS -->\n";
echo "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/style.css\">\n";
echo "  <title>Welcome</title>\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"qd-bg-dark\">\n";
echo "  <!-- UTILS -->\n";
echo "  <!-- Navbar -->\n";
echo "  <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\">\n";
echo "    <div class=\"container\">\n";
echo "      <a class=\"qd-btn-hover px-3 logo\" href=\"index.html\">\n";
echo "        <strong>QiÐom</strong>\n";
echo "      </a>\n";
echo "\n";
echo "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navmenu\">\n";
echo "        <span class=\"navbar-toggler-icon\"></span>\n";
echo "      </button>\n";
echo "      <div class=\"collapse navbar-collapse\">\n";
echo "        <ul class=\"navbar-nav ms-auto\">\n";
echo "          <li class=\"nav-item\">\n";
echo "            <a href=\"#\" class=\"nav-link qd-btn-hover\">News</a>\n";
echo "          </li>\n";
echo "          <li class=\"nav-item\">\n";
echo "            <a href=\"impressum.html\" class=\"nav-link qd-btn-hover\">Contact</a>\n";
echo "          </li>\n";
echo "          <li class=\"nav-item\">\n";
echo "            <a href=\"#\" class=\"nav-link qd-btn-hover\">Login</a>\n";
echo "          </li>\n";
echo "        </ul>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </nav>\n";
echo "\n";
echo "  <!-- Background Banner -->\n";
echo "  <div class=\"banner\">\n";
echo "    <img src=\"img/banner.png\" alt=\"cool banner\" class=\"img-fluid\">\n";
echo "  </div>\n";
echo "\n";
echo "  <!-- CONTENT -->\n";
echo "  <div class=\"container-fluid px-md-3 px-0\">\n";
echo "\n";
echo "    <!-- Display -->\n";
echo "    <div class=\"row mt-0 mx-0 m-md-4 \">\n";
echo "\n";
echo "      <!-- Carousel -->\n";
echo "      <div class=\" col-lg-8\">\n";
echo "        <div id=\"carouselExampleFade\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\n";
echo "          <div class=\"carousel-inner\">\n";
echo "            <div class=\"carousel-item active\">\n";
echo "              <img src=\"img/carousel/a.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/b.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/c.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/d.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/e.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/f.jpeg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "            <div class=\"carousel-item\">\n";
echo "              <img src=\"img/carousel/g.jpg\" class=\"d-block w-100\" alt=\"...\">\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"prev\">\n";
echo "            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n";
echo "            <span class=\"visually-hidden\">Previous</span>\n";
echo "          </button>\n";
echo "          <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"next\">\n";
echo "            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n";
echo "            <span class=\"visually-hidden\">Next</span>\n";
echo "          </button>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "      <!-- End of Carousel -->\n";
echo "\n";
echo "      <!-- Welcome text -->\n";
echo "      <div class=\"container col-lg-4 p-4 d-flex flex-column\">\n";
echo "        <div class=\"container box-1 p-4\">\n";
echo "          <h2 class=\"qd-text-col-light2 logo fs-2 fs-xl-2\">Welcome : QiÐom</h2>\n";
echo "          <p class=\"text-light pt-2\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est sunt, facilis velit esse nobis aliquid nemo, maiores sequi voluptatum quas assumenda doloribus doloremque. Asperiores itaque, eius beatae aut deleniti.\n";
echo "            <br>Ab voluptatibus tempora, eveniet fugiat ullam quia.</p>\n";
echo "          <div class=\"input-group mb-3\">\n";
echo "            <input type=\"text\" class=\"form-control fst-italic\" placeholder=\"Your E-Mail\" aria-label=\"email\" aria-describedby=\"button-addon2\">\n";
echo "            <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"button-addon2\">Newsletter</button>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "\n";
echo "\n";
echo "        <!-- StartButtons1 -->\n";
echo "        <div class=\"container mt-auto pt-2 d-none d-xxl-grid\" id=\"startbuttons\">\n";
echo "          <div class=\"row g-1 \">\n";
echo "\n";
echo "            <div class=\"col-6 start-button-parent \">\n";
echo "              <div class=\"start-button-child sb-login\">\n";
echo "                <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                  Login\n";
echo "                </a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"col-6 start-button-parent \">\n";
echo "              <div class=\"start-button-child sb-news\">\n";
echo "                <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                  News\n";
echo "                </a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"col-6 start-button-parent \">\n";
echo "              <div class=\"start-button-child sb-contact\">\n";
echo "                <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                  Contact\n";
echo "                </a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"col-6 start-button-parent \">\n";
echo "              <div class=\"start-button-child sb-impressum\">\n";
echo "                <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                  Impress\n";
echo "                </a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <!-- End of StartButtons1 -->\n";
echo "\n";
echo "      </div>\n";
echo "      <!-- End of Welcome text -->\n";
echo "\n";
echo "      <!-- StartButtons2 -->\n";
echo "      <div class=\"container mt-2 pt-2 d-xxl-none\">\n";
echo "        <div class=\"row g-1 startbutton2\">\n";
echo "\n";
echo "          <div class=\"col-lg-3 col-6 start-button-parent \">\n";
echo "            <div class=\"start-button-child sb-login\">\n";
echo "              <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                Login\n";
echo "              </a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-3 col-6 start-button-parent \">\n";
echo "            <div class=\"start-button-child sb-news\">\n";
echo "              <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                News\n";
echo "              </a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-3 col-6 start-button-parent \">\n";
echo "            <div class=\"start-button-child sb-contact\">\n";
echo "              <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                Contact\n";
echo "              </a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-3 col-6 start-button-parent \">\n";
echo "            <div class=\"start-button-child sb-impressum\">\n";
echo "              <a class=\"start-button-grandchild\" href=\"#\">\n";
echo "                Impress\n";
echo "              </a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "        </div>\n";
echo "      </div>\n";
echo "      <!-- End of StartButtons2 -->\n";
echo "\n";
echo "\n";
echo "    </div>\n";
echo "    <!-- End of Display -->\n";
echo "\n";
echo "  </div>\n";
echo "  <!-- End of CONTENT -->\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "  <!-- Bootstrap Bundle with Popper -->\n";
echo "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n";
echo "\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";
echo "\n";
?>